name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pip=23.3.1
  - requests=2.24.0
  - scikit-learn=1.5.2
  - pandas=2.1.3
  - pip:
      - mlflow==2.18.0
      - wandb==0.21.4
      - git+https://github.com/mha2112/Project-Build-an-ML-Pipeline-Starter.git#egg=wandb-utils&subdirectory=components
